### PR TITLE
added schema previews

### LINKED ISSUE #27: Scrollable section in previews for schema
* Add to the static preview section a scrollable area
* Able to view the list of schemas for that file
* should be a component

### PR DESCRIPTION
**Pull request by BANANAPEEL202**

### CODE REVIEW

**Comment by BANANAPEEL202** [comment]
Screenshot 2024-10-12 at 6 36 36 PM
@SreeDan is this what schemas r supposed to look like

**Comment by SreeDan** [comment]
@BANANAPEEL202 It looks really good! Can you add a way to search for schema names. For example, you can start searching for a schema and the matching ones show up?

**Comment by BANANAPEEL202** [comment]
@SreeDan check now

**Comment by SreeDan** [comment]
> @SreeDan check now

Looks great! ~~for searching don't make it case sensitive~~ (Im dumb i think i just fat fingered, its good right now)

**Review by SreeDan — DISMISSED** [review]

**Comment by BANANAPEEL202** [comment]
not sure what happened. can u reapprove

**Review by SreeDan — DISMISSED** [review]

**Review by SreeDan — APPROVED** [review]

**Review by SreeDan — DISMISSED** [review]

**Review by SreeDan — APPROVED** [review]

**Pull request merged**
